### ISSUE TITLE
java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by curiosity-a** [lumien231/Perfect-Spawn#10]
I'm running Obscurity modpack v1.1.16 (with non-essential mods disabled for performance).
Perfect Spawn keep accessing and transforming every class in existence and this clutters permgen until java runs out of memory. Also FML is reporting memory leaks. Removing this mod from the pack fixes this issue.
I understand that "it's not a bug, it's a feature" (as pointed out in mod description), but it would be nice to see some solution or workaround for this issue other than removing the mod altogether. Maybe add advanced setup through which user would be able to tell exactly what classes should be patched.

**Comment by lumien231** [comment]
Ehhh no. Perfect Spawn transforms DedicatedServer,BlockBed & any existing WorldProviders. It logging every class it comes across was a debug thing i forgot to removed and fixed in 1.8. But i probably won't make another update for 1.7.10. If you run out of Perm Gen increase it, after a certain amount of mods it's generally used up. For the memory leaks could you please post your log?

**Comment by curiosity-a** [comment]
I'm not sure about memory leak being related to Perfect Spawn anymore. I did some search and turns out it's still present, but happens much more rarely. Anyway, here is the log: https://dl.dropboxusercontent.com/u/21695479/fml-client-perfectspawn-memory.zip
You can search for words "may have leaked" to see actual messages.

I'm not an expert in java, but from what I gather every access to metadata takes a bit out of permgen. And you seem to be accessing a lot of it. If this is just for debug, hopefully the issue would be gone in 1.8.

As for increasing permgen, I'm running 32bit java. Not much memory to work with. And I have only 2GB anyway.
